/**
 * This code was generated by Builder.io.
 */
import React from "react";

function CategoryTabs({ categories }) {
  return (
    <nav className="flex gap-1 mt-3.5 text-xs font-medium text-black whitespace-nowrap">
      {categories.map((category, index) => (
        <button
          key={index}
          className={`px-4 py-2 rounded-[50px] shadow-[0px_1px_5px_rgba(0,0,0,0.25)] ${
            category === "Indian" ? "bg-red-900 text-white" : "bg-white"
          }`}
        >
          {category}
        </button>
      ))}
    </nav>
  );
}

export default CategoryTabs;
