/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SearchBar from "./SearchBar";
import CategoryTabs from "./CategoryTabs";
import MenuSection from "./MenuSection";

function IndianFoodMenu() {
  const categories = [
    "Continental",
    "Asian",
    "Chinese",
    "Tandoor",
    "Indian",
    "Goan",
  ];
  const menuSections = [
    {
      title: "Soups",
      items: [
        { name: "Veg Chefs Special Soup", price: 120 },
        { name: "Chicken Chefs Special Soup", price: 130 },
        { name: "Tomato Shorba", price: 90 },
      ],
    },
    {
      title: "Starter",
      items: [{ name: "Masala Omelet", price: null }],
    },
    {
      title: "Gravy",
      items: [
        { name: "Veg Kadai", price: 200 },
        { name: "Veg Kolhapuri", price: 200 },
        { name: "Veg Handi", price: 210 },
        { name: "Mutter Mushroom Masala", price: 210 },
        { name: "Paneer kadai", price: 210 },
        { name: "Paneer Butter Masala", price: 220 },
        { name: "Paneer Masala", price: 220 },
        { name: "Paneer Tikka Masala", price: 260 },
        { name: "Matar Paneer", price: 210 },
        { name: "Palak paneer", price: 210 },
        { name: "Dal Tadka", price: 140 },
        { name: "Dal Fry", price: 140 },
        { name: "Chefs Special Veg Gravy", price: 230 },
        { name: "Butter Chicken", price: 230 },
        { name: "Chicken Tikka Masala", price: 330 },
        { name: "Chicken Korma", price: 260 },
        { name: "Chefs Special Non-Veg", price: 340 },
        { name: "Veg Hydrabadi", price: 280 },
        { name: "Chicken Kolhapuri", price: 230 },
        { name: "Chicken Handi", price: 240 },
        { name: "Chicken Kadai", price: 240 },
        { name: "Chicken Masala", price: 240 },
        { name: "Mutton Masala", price: 320 },
        { name: "Veg Makhani", price: null },
      ],
    },
    {
      title: "Salads",
      items: [{ name: "Green Salad", price: 60 }],
    },
    {
      title: "Rice",
      items: [
        { name: "Steamed Rice", price: 110 },
        { name: "Jira Rice", price: 110 },
        { name: "Veg Pulao", price: 170 },
      ],
    },
    {
      title: "Biryani",
      items: [
        { name: "Veg Biryani", price: 170 },
        { name: "Egg Biryani", price: 180 },
        { name: "Prawns Biryani", price: 340 },
        { name: "Chicken Biryani", price: 280 },
        { name: "Mutton Biryani", price: 340 },
      ],
    },
  ];

  return (
    <main className="flex overflow-hidden flex-col px-6 pt-12 pb-16 mx-auto w-full tracking-tight max-w-[480px]">
      <Header />
      <h1 className="mt-4 text-lg font-bold text-red-900">
        <span className="text-black">Choose </span>
        <br />
        <span className="text-black">Your Favorite </span>Food
      </h1>
      <SearchBar />
      <CategoryTabs categories={categories} />
      <h2 className="self-start mt-5 text-base font-bold text-black">Indian</h2>
      <hr className="shrink-0 max-w-full h-px w-[380px]" />
      <section className="flex gap-5 mt-2.5 w-full">
        {menuSections.map((section, index) => (
          <MenuSection key={index} {...section} />
        ))}
      </section>
    </main>
  );
}

export default IndianFoodMenu;
