/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MenuSection({ title, items }) {
  return (
    <section className="flex flex-col items-start text-sm font-medium text-red-900">
      <h3>{title}</h3>
      <ul className="self-stretch mt-2.5 text-xs leading-4 text-black">
        {items.map((item, index) => (
          <li key={index}>
            {item.name}
            {item.price && <span className="float-right">Rs {item.price}</span>}
          </li>
        ))}
      </ul>
    </section>
  );
}

export default MenuSection;
