/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SearchBar from "./SearchBar";
import CategoryTabs from "./CategoryTabs";
import MenuSection from "./MenuSection";

function AsianFoodMenu() {
  const categories = [
    "Continental",
    "Asian",
    "Chinese",
    "Tandoor",
    "Indian",
    "Goan",
  ];
  const menuItems = [
    { name: "Steamed Momos", price: 170 },
    { name: "Steamed Momos Chicken", price: 190 },
    { name: "Pan Fried Momos", price: 170 },
    { name: "Pan Fried Momos Chicken", price: 190 },
    { name: "Fried Momos Veg", price: 170 },
    { name: "Fried Momos Chicken", price: 190 },
    { name: "Kurkure Momos Veg", price: 180 },
    { name: "Kurkure Momos Chicken", price: 210 },
    { name: "Schezwan Tossed Momos(Veg)", price: 180 },
    { name: "Schezwan Tossed Momos Chicken", price: 210 },
    { name: "Butter Garlic Momos", price: 170 },
    { name: "Butter Garlic Momos Chicken", price: 210 },
    { name: "Momos Platter Veg", price: 330 },
    { name: "Momos Platter Chicken", price: 390 },
    { name: "Panner Momo", price: 170 },
    { name: "Tandoori Momos Veg", price: 180 },
    { name: "Tandoori Momos Chicken", price: 210 },
  ];

  return (
    <main className="flex overflow-hidden flex-col px-6 pt-12 pb-80 mx-auto w-full tracking-tight max-w-[480px]">
      <Header />
      <h1 className="mt-4 text-lg font-bold text-red-900">
        <span className="text-black">Choose </span>
        <br />
        <span className="text-black">Your Favorite </span>Food
      </h1>
      <SearchBar />
      <CategoryTabs categories={categories} />
      <MenuSection menuItems={menuItems} />
    </main>
  );
}

export default AsianFoodMenu;
