/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MenuSection({ menuItems }) {
  return (
    <section>
      <h2 className="self-start mt-5 text-base font-bold text-black">Asian</h2>
      <hr className="shrink-0 h-px mt-2.5" />
      <div className="flex gap-5 justify-between self-start mt-2.5">
        <div className="flex flex-col">
          <h3 className="self-start text-sm font-medium text-red-900">Momos</h3>
          <ul className="mt-2.5 text-xs leading-4 text-black">
            {menuItems.map((item, index) => (
              <li key={index}>{item.name}</li>
            ))}
          </ul>
        </div>
        <div className="flex flex-col items-start self-start text-xs text-black whitespace-nowrap">
          <h3 className="self-stretch text-xs font-medium text-red-900">
            Price
          </h3>
          <ul className="mt-3 leading-4">
            {menuItems.map((item, index) => (
              <li key={index}>{item.price}</li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}

export default MenuSection;
