/**
 * This code was generated by Builder.io.
 */
import React from "react";
import WelcomeMessage from "./WelcomeMessage";
import MenuButton from "./MenuButton";

function ChefsBhojan() {
  return (
    <main className="flex overflow-hidden flex-col items-center px-14 pt-56 pb-32 mx-auto w-full tracking-tight bg-yellow-400 max-w-[480px]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/aeaacee752899b84be3863a1bd02618ed9ae4d3b4773b20636daefa26a474165?apiKey=eb2769a799454c22a06552d614e601b9&&apiKey=eb2769a799454c22a06552d614e601b9"
        alt="Chefs Bhojan logo"
        className="object-contain self-stretch w-full aspect-[1.2]"
      />
      <WelcomeMessage />
      <MenuButton />
    </main>
  );
}

export default ChefsBhojan;
