/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import FoodSearch from "./FoodSearch";
import CategoryTabs from "./CategoryTabs";
import MenuSection from "./MenuSection";
import { useEffect } from "react";
import { useState } from "react";

function MyComponent() {

  const [menu, setMenu] = useState([]);

  useEffect(() => {
    // Replace the URL with your API endpoint
    fetch("https://localhost:5173/menu")
      .then((response) => response.json())
      .then((data) => setMenu(data))
      .catch((error) => console.error("Error fetching menu:", error));
  }, []);

  return (
    <main className="flex overflow-hidden flex-col px-6 py-10 mx-auto w-full tracking-tight max-w-[480px]">
      <Header />
      <h1 className="mt-4 text-lg font-bold text-red-900">
        <span className="text-black">Choose </span>
        <br />
        <span className="text-black">Your Favorite </span>Food
      </h1>
      <FoodSearch />
      <CategoryTabs />
      <h2 className="self-start mt-5 text-base font-bold text-black">
        Continental
      </h2>
      <hr className="shrink-0 h-px" />
      <div className="flex gap-5 mt-2.5 w-full">
        <MenuSection
          title="Soups"
          items={[
            { name: "Cream of Mushroom Soup", price: 120 },
            { name: "Cream of Chicken Soup", price: 140 },
          ]}
        />
        <MenuSection
          title="Starter"
          items={[
            { name: "French Fries", price: 140 },
            { name: "Chessy French Fries", price: 170 },
            { name: "Potato Wedges", price: 150 },
            { name: "BBQ Chicken Wings", price: 230 },
            { name: "Chicken Nuggets", price: 190 },
            { name: "Crispy Sardine", price: 150 },
          ]}
        />
        <MenuSection
          title="Sandwich"
          items={[
            { name: "Veg club Sandwich", price: 140 },
            { name: "Chicken Club Sandwich", price: 160 },
            { name: "Chicken Grilled Sandwich", price: 150 },
            { name: "Egg Sandwich", price: 140 },
          ]}
        />
        <MenuSection
          title="Pizza"
          items={[
            { name: "Mix Veg Pizza ( 8 Inches)", price: 240 },
            { name: "Chicken Pizza (8 Inches )", price: 270 },
            { name: "Sea Food Pizza (8 Inches)", price: 310 },
            { name: "Chefs Special Veg Pizza (8 Inches)", price: 270 },
            { name: "Chefs Special non-Veg Pizza (8 inches)", price: 290 },
          ]}
        />
        <MenuSection
          title="Burger"
          items={[
            { name: "Veg Burger", price: 180 },
            { name: "Paneer Burger", price: 210 },
            { name: "Chicken Burger", price: 250 },
          ]}
        />
        <MenuSection
          title="Salads"
          items={[
            { name: "Greek Salad", price: 150 },
            { name: "Mix Salad With Pomogranates", price: 170 },
            { name: "Caesar Salad With Chicken", price: 170 },
          ]}
        />
        <MenuSection
          title="Pasta"
          items={[
            { name: "Lasanga (Veg)", price: 260 },
            { name: "Lasanga (Chicken)", price: 340 },
            { name: "Pasta (Veg)", price: 190 },
            { name: "Pasta (Chicken)", price: 240 },
            { name: "Sea Food Pasta", price: 290 },
          ]}
        />
        <MenuSection
          title="Shawarma"
          items={[
            {
              name: "Chicken Shawarma (With French Fries & Salad)",
              price: 170,
            },
            {
              name: "Falafel Shawarma (With French Fries & Salad)",
              price: 130,
            },
            { name: "Paneer Shawarma (With French Fries)", price: 140 },
          ]}
        />
      </div>
    </main>
  );
}

export default MyComponent;
