/**
 * This code was generated by Builder.io.
 */
import React from "react";

function WelcomeMessage() {
  return (
    <section className="mt-36 text-lg text-center text-black">
      Welcome to Chefs Bhojan <br />
      <span className="font-bold text-red-900">Margao, Goa</span>
    </section>
  );
}

export default WelcomeMessage;
