/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MenuSection({ title, items }) {
  return (
    <section className="flex flex-col flex-1 self-start">
      <h3 className="text-sm font-medium text-red-900">{title}</h3>
      <div className="flex gap-5 justify-between self-start mt-2.5 text-xs leading-4 text-black">
        <div>
          {items.map((item, index) => (
            <div key={index}>{item.name}</div>
          ))}
        </div>
        <div className="flex flex-col whitespace-nowrap">
          {items.map((item, index) => (
            <div key={index}>{item.price}</div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default MenuSection;
