/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SearchBar from "./SearchBar";
import CategoryTabs from "./CategoryTabs";
import MenuSection from "./MenuSection";

function ChineseMenu() {
  const categories = [
    "Continental",
    "Asian",
    "Chinese",
    "Tandoor",
    "Indian",
    "Goan",
  ];
  const menuSections = [
    {
      title: "Soups",
      items: [
        { name: "Veg Manchow Soup", price: 100 },
        { name: "Chicken Manchow Soup", price: 110 },
        { name: "Veg Sweet Corn Soup", price: 100 },
        { name: "Chicken Sweet Corn Soup", price: 120 },
        { name: "Veg Hot & Sour Soup", price: 100 },
        { name: "Chicken Hot & Sour Soup", price: 100 },
        { name: "Veg Clear Soup", price: 80 },
        { name: "Chicken Clear Soup", price: 100 },
        { name: "Sea Food Tom Yum Soup", price: 100 },
      ],
    },
    {
      title: "Starter",
      items: [
        { name: "Chicken 65", price: 220 },
        { name: "Chicken Chilly", price: 220 },
        { name: "Crispy Chicken", price: 240 },
        { name: "Honey Chicken", price: 240 },
        { name: "Chicken Dry Fry", price: 230 },
        { name: "Chicken Spring Roll", price: 220 },
        { name: "Chicken Salt & Pepper", price: 240 },
        { name: "Chicken Manchurian Dry", price: 220 },
        { name: "Chicken Manchurian Gravy", price: 220 },
        { name: "Golden Fried Prawns", price: 310 },
        { name: "Prawns Chilly Dry", price: 290 },
        { name: "Prawns Chilly Gravy", price: 210 },
        { name: "Paneer Chilly Dry", price: 210 },
        { name: "Paneer Chilly Gravy", price: 210 },
        { name: "Paneer Manchurian", price: 210 },
        { name: "Veg Crispy", price: 170 },
        { name: "Veg Spring Roll", price: 150 },
        { name: "Baby Corn Chilly Dry", price: 170 },
        { name: "Baby Corn Chilly Gravy", price: 170 },
        { name: "Honey Sesame Potato", price: 170 },
        { name: "Paneer 65", price: 210 },
        { name: "Paneer Salt & Pepper", price: 210 },
      ],
    },
    {
      title: "Starters",
      items: [
        { name: "Veg Manchurian Gravy", price: 170 },
        { name: "Veg Manchurian Dry", price: 160 },
        { name: "Gobi Manchurian gravy", price: 170 },
        { name: "Gobi Manchurian Dry", price: 160 },
        { name: "Mushroom Chilly Gravy", price: 170 },
        { name: "Mushroom Chilly Dry", price: 170 },
        { name: "Chicken Masala Lollypop", price: 240 },
      ],
    },
    {
      title: "Rice",
      items: [
        { name: "Veg Combination Fried Rice", price: 150 },
        { name: "Veg Fried Rice", price: 140 },
        { name: "Chicken Fried Rice", price: 180 },
        { name: "Egg Fried Rice", price: 150 },
        { name: "Veg Schezwan Fried Rice", price: 140 },
        { name: "Chicken Schezwan Fried Rice", price: 190 },
        { name: "Chefs Special Veg Fried Rice", price: 170 },
        { name: "Chefs Special Non-Veg Fired Rice", price: 210 },
        { name: "Mix Seafood Fried Rice", price: 250 },
        { name: "Tripple Schezwan Chicken Fried Rice", price: 250 },
      ],
    },
    {
      title: "Noodles",
      items: [
        { name: "Veg Noodles", price: 140 },
        { name: "Chicken Noodles", price: 180 },
        { name: "Egg Noodles", price: 160 },
        { name: "Veg Schezwan Noodles", price: 140 },
        { name: "Chicken Schezwan Noodles", price: 180 },
      ],
    },
  ];

  return (
    <main className="flex overflow-hidden flex-col px-6 py-12 mx-auto w-full tracking-tight max-w-[480px]">
      <Header />
      <h1 className="mt-4 text-lg font-bold text-red-900">
        <span className="text-black">Choose </span>
        <br />
        <span className="text-black">Your Favorite </span>Food
      </h1>
      <SearchBar />
      <CategoryTabs categories={categories} />
      <h2 className="self-start mt-5 text-base font-bold text-black">
        Chinese
      </h2>
      <hr className="shrink-0 h-px" />
      <section className="flex gap-5 mt-2.5 w-full">
        {menuSections.map((section, index) => (
          <MenuSection
            key={index}
            title={section.title}
            items={section.items}
          />
        ))}
      </section>
    </main>
  );
}

export default ChineseMenu;
