/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MenuSection({ title, items }) {
  return (
    <div className="flex flex-1 gap-5 justify-between">
      <div className="flex flex-col text-sm font-medium text-red-900">
        <h3>{title}</h3>
        <ul className="mt-2.5 text-xs leading-4 text-black">
          {items.map((item, index) => (
            <li key={index}>{item.name}</li>
          ))}
        </ul>
      </div>
      <div className="flex flex-col items-start self-start text-xs text-black whitespace-nowrap">
        <h4 className="self-stretch text-xs font-medium text-red-900">Price</h4>
        <ul className="mt-3">
          {items.map((item, index) => (
            <li key={index} className="leading-4">
              {item.price}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default MenuSection;
