/**
 * This code was generated by Builder.io.
 */
import React from "react";

function CategoryTabs({ categories }) {
  return (
    <nav className="flex gap-1 mt-3.5 text-xs font-medium text-black whitespace-nowrap">
      {categories.map((category, index) => (
        <button
          key={index}
          className={`px-2.5 py-2 text-center rounded-[50px] shadow-[0px_1px_5px_rgba(0,0,0,0.25)] ${
            category.active ? "text-white bg-red-900" : "bg-white"
          }`}
        >
          {category.name}
        </button>
      ))}
    </nav>
  );
}

export default CategoryTabs;
