/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MenuSection({ title, items }) {
  return (
    <section className="flex gap-5 justify-between items-start mt-2.5">
      <div className="flex flex-col self-stretch text-sm font-medium text-red-900">
        <h3 className="self-start">{title}</h3>
        <ul className="mt-2.5 text-xs leading-4 text-black">
          {items.map((item, index) => (
            <li key={index}>{item.name}</li>
          ))}
        </ul>
      </div>
      <div className="flex flex-col text-xs text-black">
        <div className="text-xs font-medium text-red-900">Price</div>
        {items.map((item, index) => (
          <div key={index} className="mt-3 leading-4">
            {item.price}
          </div>
        ))}
      </div>
    </section>
  );
}

export default MenuSection;
