/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex gap-5 justify-between items-center text-xs text-center">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/098540433167041cb3f77702624cb6e461a644e91bd28a427e5d204eb4a31d03?apiKey=eb2769a799454c22a06552d614e601b9&&apiKey=eb2769a799454c22a06552d614e601b9"
        alt=""
        className="object-contain shrink-0 self-stretch aspect-[1.2] w-[60px]"
      />
      <div className="flex flex-col self-stretch my-auto">
        <div className="self-start text-black">You are at</div>
        <div className="font-bold text-red-900">Margao, Goa</div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/1544fa085e558c7aeb32f0cf69bb35b0f144ff3d20c3bb9bba76c7e295f0f0fa?apiKey=eb2769a799454c22a06552d614e601b9&&apiKey=eb2769a799454c22a06552d614e601b9"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto aspect-[1.29] w-[31px]"
      />
    </header>
  );
}

export default Header;
